# Generated by Django 4.1.7 on 2023-05-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY'), ('CAD', 'CAD')], max_length=15),
        ),
    ]
