# Generated by Django 4.0.1 on 2022-01-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_crypto_remove_account_stock_holding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='holding',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
    ]
