# Generated by Django 4.0.1 on 2022-01-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_holding_delete_holding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
