# Generated by Django 4.0.1 on 2022-01-19 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='capital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.capital'),
            preserve_default=False,
        ),
    ]
