# Generated by Django 4.0.1 on 2022-01-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='capital',
        ),
        migrations.AddField(
            model_name='account',
            name='capitalinit',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
