# Generated by Django 4.0.1 on 2022-01-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_account_capital_capital_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='user',
            new_name='account',
        ),
    ]
