# Generated by Django 4.0.1 on 2022-01-19 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_user_capital_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to=settings.AUTH_USER_MODEL),
        ),
    ]
