# Generated by Django 4.0.1 on 2022-01-20 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_capital_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='id',
        ),
        migrations.AlterField(
            model_name='capital',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
