# Generated by Django 4.0.1 on 2022-01-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_capital_id_alter_capital_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='account',
            new_name='user',
        ),
    ]
