# Generated by Django 4.0.1 on 2022-02-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_account_capital_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY')], default='EUR', max_length=15),
            preserve_default=False,
        ),
    ]
