# Generated by Django 4.0.3 on 2022-03-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_account_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
