# Generated by Django 4.0.3 on 2022-03-31 21:06

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_capital'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
