# Generated by Django 4.0.1 on 2022-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('shortName', models.CharField(blank=True, max_length=30, null=True)),
                ('longName', models.CharField(blank=True, max_length=30, null=True)),
                ('exchange', models.CharField(blank=True, max_length=10, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=50, null=True)),
                ('regularMarketPrice', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
