# Generated by Django 4.1.7 on 2023-05-11 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY'), ('CAD', 'CAD')], default='EUR', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holding',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY'), ('CAD', 'CAD')], max_length=15),
        ),
    ]
