# Generated by Django 4.0.1 on 2022-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, max_length=10, null=True)),
                ('shortName', models.CharField(blank=True, max_length=30, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('regularMarketPrice', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
