# Generated by Django 4.1.7 on 2024-01-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='currency',
        ),
    ]
