# Generated by Django 4.1.7 on 2023-05-11 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holdings', '0002_capital_currency_alter_holding_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('snapshot_hook', models.CharField(choices=[('daily', 'daily'), ('overview', 'overview'), ('on_update', 'on_update'), ('manual', 'manual')], max_length=10)),
                ('portfolio', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OverviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('snapshot_hook', models.CharField(choices=[('daily', 'daily'), ('overview', 'overview'), ('on_update', 'on_update'), ('manual', 'manual')], max_length=10)),
                ('overview', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
