# Generated by Django 4.0.3 on 2022-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_portfoliosnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
