# Generated by Django 4.0.1 on 2022-01-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_crypto_alter_stock_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
