# Generated by Django 4.0.3 on 2022-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0003_alter_portfoliosnapshot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='snapshot_hook',
            field=models.CharField(choices=[('daily', 'daily'), ('on_update', 'on_update'), ('manual', 'manual')], default='daily', max_length=10),
            preserve_default=False,
        ),
    ]
