# Generated by Django 4.0.1 on 2022-01-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0004_crypto_user_stock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
