# Generated by Django 4.0.1 on 2022-01-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0006_alter_crypto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crypto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='crypto',
            constraint=models.UniqueConstraint(fields=('symbol', 'user'), name='unique_crypto'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('symbol', 'user'), name='unique_stock'),
        ),
    ]
