# Generated by Django 4.0.1 on 2022-01-11 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holdings', '0008_holding_remove_stock_user_delete_crypto_delete_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('ST', 'STOCK'), ('CR', 'CRYPTO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='holding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
