# Generated by Django 4.0.1 on 2022-01-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0009_alter_holding_currency_alter_holding_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='longName',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='regularMarketPrice',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='shortName',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='volume',
        ),
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('STOCK', 'STOCK'), ('CRYPTO', 'CRYPTO')], max_length=10),
        ),
    ]
