# Generated by Django 4.0.1 on 2022-01-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0010_remove_holding_currency_remove_holding_exchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTemplate',
            fields=[
                ('assettemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='holdings.assettemplate')),
                ('fromCurrency', models.CharField(max_length=50)),
            ],
            bases=('holdings.assettemplate',),
        ),
        migrations.CreateModel(
            name='StockTemplate',
            fields=[
                ('assettemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='holdings.assettemplate')),
                ('sector', models.CharField(max_length=50)),
                ('longName', models.CharField(max_length=50)),
            ],
            bases=('holdings.assettemplate',),
        ),
    ]
