# Generated by Django 4.0.1 on 2022-01-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0011_assettemplate_cryptotemplate_stocktemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettemplate',
            name='type',
        ),
    ]
