# Generated by Django 4.0.1 on 2022-01-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0012_remove_assettemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettemplate',
            name='shortName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
