# Generated by Django 4.0.1 on 2022-01-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0013_assettemplate_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holdings.assettemplate'),
        ),
    ]
