# Generated by Django 4.0.1 on 2022-01-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0014_holding_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='template',
        ),
        migrations.AddField(
            model_name='holding',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='holdings.assettemplate'),
        ),
    ]
