# Generated by Django 4.0.1 on 2022-01-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0015_remove_holding_template_holding_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='name',
            new_name='symbol',
        ),
    ]
