# Generated by Django 4.0.1 on 2022-01-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0017_alter_holding_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STOCK', 'STOCK'), ('CRYPTO', 'CRYPTO')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdings.assettype'),
        ),
    ]
