# Generated by Django 4.0.1 on 2022-01-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0018_assettype_alter_holding_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettemplate',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='holdings.assettype'),
            preserve_default=False,
        ),
    ]
