# Generated by Django 4.0.1 on 2022-01-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0019_assettemplate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='type',
        ),
    ]
