# Generated by Django 4.0.1 on 2022-01-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0020_remove_holding_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='symbol',
            new_name='template',
        ),
    ]
