# Generated by Django 4.0.1 on 2022-01-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0021_rename_symbol_holding_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='template',
            new_name='symbol',
        ),
    ]
