# Generated by Django 4.0.1 on 2022-01-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0022_rename_template_holding_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettemplate',
            name='type',
            field=models.CharField(choices=[('STOCK', 'STOCK'), ('CRYPTO', 'CRYPTO')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
