# Generated by Django 4.0.1 on 2022-01-18 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0023_alter_assettemplate_type_delete_assettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('STOCK', 'STOCK'), ('CRYPTO', 'CRYPTO')], default='STOCK', max_length=10),
            preserve_default=False,
        ),
    ]
