# Generated by Django 4.0.1 on 2022-01-18 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0024_holding_date_holding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
