# Generated by Django 4.0.1 on 2022-01-19 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0025_alter_holding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
