# Generated by Django 4.0.1 on 2022-01-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0027_capital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
