# Generated by Django 4.0.1 on 2022-01-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0028_delete_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='action',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
            preserve_default=False,
        ),
    ]
