# Generated by Django 4.0.1 on 2022-01-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0029_holding_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettemplate',
            name='type',
            field=models.CharField(choices=[('stock', 'stock'), ('crypto', 'crypto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('stock', 'stock'), ('crypto', 'crypto')], max_length=10),
        ),
    ]
