# Generated by Django 4.0.1 on 2022-01-24 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0030_alter_assettemplate_type_alter_holding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
