# Generated by Django 4.0.1 on 2022-01-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0032_remove_stocktemplate_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktemplate',
            name='longName',
            field=models.CharField(max_length=100),
        ),
    ]
