# Generated by Django 4.0.1 on 2022-01-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0033_alter_stocktemplate_longname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptotemplate',
            name='assettemplate_ptr',
        ),
        migrations.RemoveField(
            model_name='stocktemplate',
            name='assettemplate_ptr',
        ),
        migrations.AddField(
            model_name='holding',
            name='currency',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='AssetTemplate',
        ),
        migrations.DeleteModel(
            name='CryptoTemplate',
        ),
        migrations.DeleteModel(
            name='StockTemplate',
        ),
    ]
