# Generated by Django 4.0.1 on 2022-01-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0034_remove_cryptotemplate_assettemplate_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='currency',
        ),
    ]
