# Generated by Django 4.0.1 on 2022-01-26 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0035_remove_holding_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('stock', 'stock'), ('crypto', 'crypto'), ('etf', 'etf')], max_length=10),
        ),
    ]
