# Generated by Django 4.0.1 on 2022-01-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0036_alter_holding_date_alter_holding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('stock', 'stock'), ('crypto', 'crypto')], max_length=10),
        ),
    ]
