# Generated by Django 4.0.1 on 2022-01-30 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0037_alter_holding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
