# Generated by Django 4.0.1 on 2022-01-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0038_alter_holding_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='action',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10),
        ),
    ]
