# Generated by Django 4.0.1 on 2022-02-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0039_alter_holding_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='action',
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
