# Generated by Django 4.0.1 on 2022-02-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0040_remove_holding_action_alter_holding_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=15),
        ),
    ]
