# Generated by Django 4.0.1 on 2022-02-04 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0041_alter_holding_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
