# Generated by Django 4.0.1 on 2022-02-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0042_holding_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='currency',
            field=models.CharField(default='eur', max_length=15),
            preserve_default=False,
        ),
    ]
