# Generated by Django 4.0.1 on 2022-02-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0043_holding_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], max_length=10),
        ),
    ]
