# Generated by Django 4.0.1 on 2022-02-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0044_alter_holding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], max_length=15),
        ),
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('stock', 'stock'), ('crypto', 'crypto')], max_length=10),
        ),
    ]
