# Generated by Django 4.0.1 on 2022-02-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0046_alter_holding_currency_alter_holding_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
