# Generated by Django 4.0.1 on 2022-02-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0047_rename_price_holding_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.CharField(choices=[('stock', 'stock'), ('crypto', 'crypto')], max_length=10),
        ),
    ]
