# Generated by Django 4.0.1 on 2022-02-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0048_alter_holding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY')], default='EUR', max_length=15),
        ),
    ]
