# Generated by Django 4.0.3 on 2022-04-01 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0051_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='purchase_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
