# Generated by Django 4.0.3 on 2022-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0052_alter_holding_purchase_price_alter_holding_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='crypto',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='capital',
            name='stock',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
